apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVSnVscWh2SnZwakVBOHNPUnh3Tk1TZ2htaGE4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSTFNRFl5TURFMU1qYzFORm9YRFRJMU1EY3lNREUxTWpjMU5Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNUZWp2U1lqcmIyZWpXbkx1MzVYVHFMaXVNZHgyMllMVlJYego4aU9mTDA4Y1Z1dittZ2oyNmRQL01CQ2tiRDhaMlc0dFRodS9CM242MU0xUkN4L1ZUNlJ2QUtIWGJtb0pUTTMwCjV0L25IdGN1TkY2N3cwdDlreittTDliUC8vVnArUDZYT3Y4blJHRGdWbllMdjNPblFhUWhveXErSnVtSk9KWkkKRGxScmRPdUZQUW9DUjR5T0VaTWMyWmNnOTZyM01kckRwcWhmM2ZNZHdGNVJ0Z1I4S000RnFmcUFQcnZ3K3pqLwpPUy95V1lkZ1Z3U0VVRXVxek9paUZkTjNJTVBoUElFSWFvNjVXMHkwMDhxd3REaHBpZkN0L1hRb0JYRFhuNzR3CkNEY2VWUTBTVk1ERzN1VXM5UGpVRFNqMTlrRlVpOFB1bjcvbjlFU05HNGt1OVZBL3FRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVUm0vdk5XaWFCQUJuTk1VVlpSemR6N2phL1JNd0h3WURWUjBqQkJnd0ZvQVVSbS92TldpYQpCQUJuTk1VVlpSemR6N2phL1JNd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFiYlFsWlRHSFBmTEUrNTJYV0FLUDRQaFZEaGNNZWtqRXdKVFJJNmlhOFFpK3BNVG9SMVk4VGhOMzN1dnEKOXBFZW1vVTNIenpUcHVHRjVmc2R3L3FxcnlQOXBOYURWMXkrYkpyNzNuYWt0Q3dldDg0a2RHM1B3dW5wTUpqSApmVnJDOHZQVlF5QjVvS3poMUdEVk1EamZQdFRYMWxKR3BIR28rVGhqbXlZQTdGVU5oVXg5OTVoRUdiY0hmNVhUCklNSUlMcm1MN1p5VHkrZXduejIwYUFKZG9McFk1RVIyaWwzOEZTUm5ycEwrbXlJSFBpYTJuaGdVdktwbnByT2oKZ1lqdURIVmFIVTFVbWt3MXg1cUxVaDFYeUFaOUNSWHRnSzV0bkV3SEJNbkJ5RjMyVFpmc1IwWUpBRHUwZUFuRgpaYXpZeEpObW5aT0U0cEc3K0g1TWdOMFh1UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None