apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv/mysql/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain