apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wp
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv/wp/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain