- name: 'hosts'
  hosts: all
  become: yes
  tasks:
    - name: 'Execute a script'
      script: '/tmp/install_script.sh'
    - name: 'Start httpd service'   
      service:
        name: 'httpd'   
        state: 'started' 
    - name: 'Add a line to index file'
      lineinfile:
        path: '/var/www/html/index.html'
        line: 'Welcome to ansible-beginning course'
        create: true
    - name: 'Add new user'
      user:
        name: 'web_user'
        uid: 1040
        group: 'developers'